<?xml version="1.0"?>
<!DOCTYPE definition [
	<!ELEMENT definition     (version,entry+)>
	<!ELEMENT version        (#PCDATA)>

	<!ELEMENT entry          (subpath,mode,item*,entry*)>
	<!ELEMENT mode           (#PCDATA)>

	<!ELEMENT subpath        (subpath_type,path,subpath_field*)>
	<!ELEMENT subpath_type   (#PCDATA)>
	<!ELEMENT path           (#PCDATA)>

	<!ELEMENT subpath_field  (index,name)>
	<!ELEMENT index          (#PCDATA)>
	<!ELEMENT name           (#PCDATA)>

	<!ELEMENT item           (name,pattern,field+)>
	<!ELEMENT pattern        (#PCDATA)>

	<!ELEMENT field          (index,name,type,option+)>
	<!ELEMENT type           (#PCDATA)>

	<!ELEMENT option         (name,string)>
	<!ELEMENT string         (#PCDATA)>
]>
<definition>
	<version>1.8.9</version>
	<entry>
		<subpath>
			<subpath_type>constant</subpath_type>
			<path>/proc/fs/lustre</path>
		</subpath>
		<mode>directory</mode>
		<entry>
			<subpath>
				<subpath_type>constant</subpath_type>
				<path>health_check</path>
			</subpath>
			<mode>file</mode>
			<item>
				<name>health</name>
				<pattern>(.+)</pattern>
				<field>
					<index>1</index>
					<name>health</name>
					<type>string</type>
					<option>
						<name>host</name>
						<string>NA</string>
					</option>
					<option>
						<name>plugin</name>
						<string>NA</string>
					</option>
					<option>
						<name>plugin_instance</name>
						<string>NA</string>
					</option>
					<option>
						<name>type</name>
						<string>NA</string>
					</option>
					<option>
						<name>type_instance</name>
						<string>NA</string>
					</option>
				</field>
			</item>
		</entry>
		<entry>
			<subpath>
				<subpath_type>constant</subpath_type>
				<path>version</path>
			</subpath>
			<mode>file</mode>
			<item>
				<name>lustre_version</name>
				<pattern>lustre: ([[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+)</pattern>
				<field>
					<index>1</index>
					<name>version</name>
					<type>string</type>
					<option>
						<name>host</name>
						<string>NA</string>
					</option>
					<option>
						<name>plugin</name>
						<string>NA</string>
					</option>
					<option>
						<name>plugin_instance</name>
						<string>NA</string>
					</option>
					<option>
						<name>type</name>
						<string>NA</string>
					</option>
					<option>
						<name>type_instance</name>
						<string>NA</string>
					</option>
				</field>
			</item>
			<item>
				<name>kernel_type</name>
				<pattern>kernel: (patchless_client)</pattern>
				<field>
					<index>1</index>
					<name>kernel_type</name>
					<type>string</type>
					<option>
						<name>host</name>
						<string>NA</string>
					</option>
					<option>
						<name>plugin</name>
						<string>NA</string>
					</option>
					<option>
						<name>plugin_instance</name>
						<string>NA</string>
					</option>
					<option>
						<name>type</name>
						<string>NA</string>
					</option>
					<option>
						<name>type_instance</name>
						<string>NA</string>
					</option>
				</field>
			</item>
			<item>
				<name>build_version</name>
				<pattern>build:  (.+)</pattern>
				<field>
					<index>1</index>
					<name>build_version</name>
					<type>string</type>
					<option>
						<name>host</name>
						<string>NA</string>
					</option>
					<option>
						<name>plugin</name>
						<string>NA</string>
					</option>
					<option>
						<name>plugin_instance</name>
						<string>NA</string>
					</option>
					<option>
						<name>type</name>
						<string>NA</string>
					</option>
					<option>
						<name>type_instance</name>
						<string>NA</string>
					</option>
				</field>
			</item>
		</entry>
		<entry>
			<subpath>
				<subpath_type>constant</subpath_type>
				<path>mds</path>
			</subpath>
			<mode>directory</mode>
			<entry>
				<subpath>
					<subpath_type>regular_expression</subpath_type>
					<path>(^.+-MDT[0-9a-fA-F]+$)</path>
					<subpath_field>
						<index>1</index>
						<name>mdt_name</name>
					</subpath_field>
				</subpath>
				<mode>directory</mode>
				<entry>
					<!-- mds_stats_counter_init() -->
					<subpath>
						<subpath_type>constant</subpath_type>
						<path>stats</path>
					</subpath>
					<mode>file</mode>
					<item>
						<name>md_stats_open</name>
						<pattern>open +([[:digit:]]+) samples .+</pattern>
						<field>
							<index>1</index>
							<name>open</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:mdt_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>md_stats</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string></string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>open</string>
							</option>
						</field>
					</item>
					<item>
						<name>md_stats_close</name>
						<pattern>close +([[:digit:]]+) samples .+</pattern>
						<field>
							<index>1</index>
							<name>close</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:mdt_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>md_stats</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string></string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>close</string>
							</option>
						</field>
					</item>
					<item>
						<name>md_stats_mknod</name>
						<pattern>mknod +([[:digit:]]+) samples .+</pattern>
						<field>
							<index>1</index>
							<name>mknod</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:mdt_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>md_stats</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string></string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>mknod</string>
							</option>
						</field>
					</item>
					<item>
						<name>md_stats_link</name>
						<pattern>link +([[:digit:]]+) samples .+</pattern>
						<field>
							<index>1</index>
							<name>link</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:mdt_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>md_stats</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string></string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>link</string>
							</option>
						</field>
					</item>
					<item>
						<name>md_stats_unlink</name>
						<pattern>unlink +([[:digit:]]+) samples .+</pattern>
						<field>
							<index>1</index>
							<name>unlink</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:mdt_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>md_stats</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string></string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>unlink</string>
							</option>
						</field>
					</item>
					<item>
						<name>md_stats_mkdir</name>
						<pattern>mkdir +([[:digit:]]+) samples .+</pattern>
						<field>
							<index>1</index>
							<name>mkdir</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:mdt_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>md_stats</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string></string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>mkdir</string>
							</option>
						</field>
					</item>
					<item>
						<name>md_stats_rmdir</name>
						<pattern>rmdir +([[:digit:]]+) samples .+</pattern>
						<field>
							<index>1</index>
							<name>rmdir</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:mdt_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>md_stats</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string></string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>rmdir</string>
							</option>
						</field>
					</item>
					<item>
						<name>md_stats_rename</name>
						<pattern>rename +([[:digit:]]+) samples .+</pattern>
						<field>
							<index>1</index>
							<name>rename</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:mdt_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>md_stats</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string></string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>rename</string>
							</option>
						</field>
					</item>
					<item>
						<name>md_stats_getattr</name>
						<pattern>getattr +([[:digit:]]+) samples .+</pattern>
						<field>
							<index>1</index>
							<name>getattr</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:mdt_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>md_stats</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string></string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>getattr</string>
							</option>
						</field>
					</item>
					<item>
						<name>md_stats_setattr</name>
						<pattern>setattr +([[:digit:]]+) samples .+</pattern>
						<field>
							<index>1</index>
							<name>setattr</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:mdt_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>md_stats</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string></string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>setattr</string>
							</option>
						</field>
					</item>
					<item>
						<name>md_stats_getxattr</name>
						<pattern>getxattr +([[:digit:]]+) samples .+</pattern>
						<field>
							<index>1</index>
							<name>getxattr</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:mdt_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>md_stats</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string></string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>getxattr</string>
							</option>
						</field>
					</item>
					<item>
						<name>md_stats_setxattr</name>
						<pattern>setxattr +([[:digit:]]+) samples .+</pattern>
						<field>
							<index>1</index>
							<name>setxattr</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:mdt_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>md_stats</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string></string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>setxattr</string>
							</option>
						</field>
					</item>
					<item>
						<name>md_stats_statfs</name>
						<pattern>statfs +([[:digit:]]+) samples .+</pattern>
						<field>
							<index>1</index>
							<name>statfs</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:mdt_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>md_stats</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string></string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>statfs</string>
							</option>
						</field>
					</item>
					<item>
						<name>md_stats_sync</name>
						<pattern>sync +([[:digit:]]+) samples .+</pattern>
						<field>
							<index>1</index>
							<name>sync</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:mdt_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>md_stats</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string></string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>sync</string>
							</option>
						</field>
					</item>
				</entry>
			</entry>
		</entry>
		<entry>
			<subpath>
				<subpath_type>constant</subpath_type>
				<path>obdfilter</path>
			</subpath>
			<mode>directory</mode>
			<entry>
				<subpath>
					<subpath_type>regular_expression</subpath_type>
					<path>(^.+-OST[0-9a-fA-F]+$)</path>
					<subpath_field>
						<index>1</index>
						<name>ost_name</name>
					</subpath_field>
				</subpath>
				<mode>directory</mode>
				<entry>
					<!-- filter_setup().
					     There are a lot of counter, only defined part of them here
					-->
					<subpath>
						<subpath_type>constant</subpath_type>
						<path>stats</path>
					</subpath>
					<mode>file</mode>
					<item>
						<name>ost_stats_read</name>
						<pattern>read_bytes +([[:digit:]]+) samples \[bytes\] [[:digit:]]+ [[:digit:]]+ ([[:digit:]]+)</pattern>
						<field>
							<index>1</index>
							<name>read_samples</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:ost_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>stats</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string></string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>read_samples</string>
							</option>
						</field>
						<field>
							<index>2</index>
							<name>read_bytes</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:ost_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>stats</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string></string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>read_bytes</string>
							</option>
						</field>
					</item>
					<item>
						<name>ost_stats_write</name>
						<pattern>write_bytes +([[:digit:]]+) samples \[bytes\] [[:digit:]]+ [[:digit:]]+ ([[:digit:]]+)</pattern>
						<field>
							<index>1</index>
							<name>write_samples</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:ost_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>stats</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string></string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>write_samples</string>
							</option>
						</field>
						<field>
							<index>2</index>
							<name>write_bytes</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:ost_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>stats</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string></string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>write_bytes</string>
							</option>
						</field>
					</item>
					<item>
						<name>ost_stats_get_page</name>
						<pattern>get_page +([[:digit:]]+) samples \[usec\]</pattern>
						<field>
							<index>1</index>
							<name>get_page</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:ost_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>stats</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string></string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>get_page</string>
							</option>
						</field>
					</item>
					<item>
						<name>ost_stats_get_page_failures</name>
						<pattern>get_page failures +([[:digit:]]+) samples \[num\]</pattern>
						<field>
							<index>1</index>
							<name>get_page_failures</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:ost_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>stats</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string></string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>get_page_failures</string>
							</option>
						</field>
					</item>
					<item>
						<name>ost_stats_cache_access</name>
						<pattern>cache_access +([[:digit:]]+) samples \[pages\]</pattern>
						<field>
							<index>1</index>
							<name>cache_access</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:ost_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>stats</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string></string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>cache_access</string>
							</option>
						</field>
					</item>
					<item>
						<name>ost_stats_cache_hit</name>
						<pattern>cache_hit +([[:digit:]]+) samples \[pages\]</pattern>
						<field>
							<index>1</index>
							<name>cache_hit</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:ost_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>stats</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string></string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>cache_hit</string>
							</option>
						</field>
					</item>
					<item>
						<name>ost_stats_cache_miss</name>
						<pattern>cache_miss +([[:digit:]]+) samples \[pages\]</pattern>
						<field>
							<index>1</index>
							<name>cache_miss</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:ost_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>stats</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string></string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>cache_miss</string>
							</option>
						</field>
					</item>
					<!-- Following comes from filter_setup()/lprocfs_alloc_obd_stats()/lprocfs_init_ops_stats()
					     Not necessarily available.
					-->
					<item>
						<name>ost_stats_getattr</name>
						<pattern>getattr +([[:digit:]]+) samples \[reqs\]</pattern>
						<field>
							<index>1</index>
							<name>getattr</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:ost_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>stats</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string></string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>getattr</string>
							</option>
						</field>
					</item>
					<item>
						<name>ost_stats_setattr</name>
						<pattern>setattr +([[:digit:]]+) samples \[reqs\]</pattern>
						<field>
							<index>1</index>
							<name>setattr</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:ost_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>stats</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string></string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>setattr</string>
							</option>
						</field>
					</item>
					<item>
						<name>ost_stats_punch</name>
						<pattern>punch +([[:digit:]]+) samples \[reqs\]</pattern>
						<field>
							<index>1</index>
							<name>punch</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:ost_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>stats</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string></string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>punch</string>
							</option>
						</field>
					</item>
					<item>
						<name>ost_stats_sync</name>
						<pattern>sync +([[:digit:]]+) samples \[reqs\]</pattern>
						<field>
							<index>1</index>
							<name>sync</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:ost_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>stats</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string></string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>sync</string>
							</option>
						</field>
					</item>
					<item>
						<name>ost_stats_destroy</name>
						<pattern>destroy +([[:digit:]]+) samples \[reqs\]</pattern>
						<field>
							<index>1</index>
							<name>destroy</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:ost_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>stats</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string></string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>destroy</string>
							</option>
						</field>
					</item>
					<item>
						<name>ost_stats_create</name>
						<pattern>create +([[:digit:]]+) samples \[reqs\]</pattern>
						<field>
							<index>1</index>
							<name>create</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:ost_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>stats</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string></string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>create</string>
							</option>
						</field>
					</item>
					<item>
						<name>ost_stats_statfs</name>
						<pattern>statfs +([[:digit:]]+) samples \[reqs\]</pattern>
						<field>
							<index>1</index>
							<name>statfs</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:ost_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>stats</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string></string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>statfs</string>
							</option>
						</field>
					</item>
					<item>
						<name>ost_stats_get_info</name>
						<pattern>get_info +([[:digit:]]+) samples \[reqs\]</pattern>
						<field>
							<index>1</index>
							<name>get_info</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:ost_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>stats</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string></string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>get_info</string>
							</option>
						</field>
					</item>
					<item>
						<name>ost_stats_set_info_async</name>
						<pattern>set_info_async +([[:digit:]]+) samples \[reqs\]</pattern>
						<field>
							<index>1</index>
							<name>set_info_async</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:ost_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>stats</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string></string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>set_info_async</string>
							</option>
						</field>
					</item>
					<item>
						<name>ost_stats_quotactl</name>
						<pattern>quotactl +([[:digit:]]+) samples \[reqs\]</pattern>
						<field>
							<index>1</index>
							<name>quotactl</name>
							<type>number</type>
							<option>
								<name>host</name>
								<string>${subpath:ost_name}</string>
							</option>
							<option>
								<name>plugin</name>
								<string>stats</string>
							</option>
							<option>
								<name>plugin_instance</name>
								<string></string>
							</option>
							<option>
								<name>type</name>
								<string>derive</string>
							</option>
							<option>
								<name>type_instance</name>
								<string>quotactl</string>
							</option>
						</field>
					</item>
				</entry>
			</entry>
		</entry>
	</entry>
</definition>
